### ISSUE TITLE
Data for 20w14~

### ISSUE THREAD

**Issue by U-siro** [tsao-chi/Unofficial-snapshot-Spigot-BuildData#1]
Can I get 20w14~ builddata, or the script?

**Comment by mio-19** [comment]
yes. https://github.com/tsao-chi/Unofficial-snapshot-Spigot-BuildData-Scripts

**Comment by mio-19** [comment]
What will you use this for?

**Comment by U-siro** [comment]
Just for fun, will try to build spigot and open server

**Comment by mio-19** [comment]
@U-siro It won't be easy
